security:
    # Configuration du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d’utilisateurs basé sur ton entité Utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Utilisation du custom authenticator
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: /

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        # Allow anonymous access to the login page
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Secure the rest of the site
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
